### ISSUE TITLE
Merge "Mint + Deposit", "Burn + Withdraw" in history table

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomobridge#68]
Columns:
- In Tx Hash
- Out Tx Hash
- Status, e.g "Mint, Deposited"
- Token: e.g "BTC"
- Amount
- Age

**Comment by kriptokar** [comment]
Gelen Tx Hash
Giden Tx Hash
Durum, örn. "Üretilmiş, Yüklenmiş"
Token: örn. "BTC"
Miktar
Yaş
